/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by auto-import scanner
// biome-ignore lint: disable
export {}
declare global {
  const ENTITY_TRAIT_NAMES: typeof import('~client/entityTraits').ENTITY_TRAIT_NAMES
  const getGame: typeof import('~client/game').getGame
  const getView: typeof import('~client/game').getView
  const init: typeof import('~client/game').init
  const startTickLoop: typeof import('~client/game').startTickLoop
  const setOnQueueChange: typeof import('~client/input').setOnQueueChange
  const getMoveQueue: typeof import('~client/input').getMoveQueue
  const advanceQueue: typeof import('~client/input').advanceQueue
  const getInspectedCell: typeof import('~client/input').getInspectedCell
  const getHoveredCell: typeof import('~client/input').getHoveredCell
  const bindInput: typeof import('~client/input').bindInput
  const Renderer: typeof import('~client/renderer').Renderer
  const settings: typeof import('~client/settings').settings
  const TRAIT_RENDERERS: typeof import('~client/traitRenderers').TRAIT_RENDERERS
  const renderTrait: typeof import('~client/traitRenderers').renderTrait
}
// for type re-export
declare global {
  // @ts-ignore
  export type { MoveStep } from '~client/input'
  import('~client/input')
  // @ts-ignore
  export type { Renderer } from '~client/renderer'
  import('~client/renderer')
}
