/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BaseEntityType: typeof import('@sf/engine').BaseEntityType
  const CELL_H: typeof import('@sf/ui').CELL_H
  const CELL_W: typeof import('@sf/ui').CELL_W
  const Dirt: typeof import('@sf/engine').Dirt
  const DirtRenderer: typeof import('@sf/ui').DirtRenderer
  const DrawContext: typeof import('@sf/ui').DrawContext
  const EntityRenderer: typeof import('@sf/ui').EntityRenderer
  const EntityTypeTrait: typeof import('@sf/engine').EntityTypeTrait
  const GroundCoverTrait: typeof import('@sf/engine').GroundCoverTrait
  const GroundCoverTraitRenderer: typeof import('@sf/ui').GroundCoverTraitRenderer
  const HealthTrait: typeof import('@sf/engine').HealthTrait
  const HealthTraitRenderer: typeof import('@sf/ui').HealthTraitRenderer
  const HungerTrait: typeof import('@sf/engine').HungerTrait
  const HungerTraitRenderer: typeof import('@sf/ui').HungerTraitRenderer
  const MoistureTrait: typeof import('@sf/engine').MoistureTrait
  const MoistureTraitRenderer: typeof import('@sf/ui').MoistureTraitRenderer
  const NameTrait: typeof import('@sf/engine').NameTrait
  const Player: typeof import('@sf/engine').Player
  const PlayerControlledTrait: typeof import('@sf/engine').PlayerControlledTrait
  const PlayerRenderer: typeof import('@sf/ui').PlayerRenderer
  const PositionTrait: typeof import('@sf/engine').PositionTrait
  const Renderer: typeof import('@sf/ui').Renderer
  const Sand: typeof import('@sf/engine').Sand
  const SandRenderer: typeof import('@sf/ui').SandRenderer
  const SpeedTrait: typeof import('@sf/engine').SpeedTrait
  const SpeedTraitRenderer: typeof import('@sf/ui').SpeedTraitRenderer
  const Stone: typeof import('@sf/engine').Stone
  const StoneRenderer: typeof import('@sf/ui').StoneRenderer
  const TICKS_PER_DAY: typeof import('@sf/state').TICKS_PER_DAY
  const Trait: typeof import('@sf/engine').Trait
  const TraitRenderer: typeof import('@sf/ui').TraitRenderer
  const Water: typeof import('@sf/engine').Water
  const WaterRenderer: typeof import('@sf/ui').WaterRenderer
  const addComponent: typeof import('@sf/state').addComponent
  const addToSpatialIndex: typeof import('@sf/state').addToSpatialIndex
  const bootstrap: typeof import('@sf/engine').bootstrap
  const buildFaces2d: typeof import('@sf/state').buildFaces2d
  const buildFaces3d: typeof import('@sf/state').buildFaces3d
  const chunkKey: typeof import('@sf/state').chunkKey
  const createEntity: typeof import('@sf/state').createEntity
  const createWorld: typeof import('@sf/state').createWorld
  const entityTypeTickSystem: typeof import('@sf/engine').entityTypeTickSystem
  const exportChunk: typeof import('@sf/engine').exportChunk
  const exportManifest: typeof import('@sf/engine').exportManifest
  const getComponent: typeof import('@sf/state').getComponent
  const getEntitiesAt: typeof import('@sf/state').getEntitiesAt
  const getEntitiesInColumn: typeof import('@sf/state').getEntitiesInColumn
  const getEntityTypeConstructor: typeof import('@sf/engine').getEntityTypeConstructor
  const getNeighborCoords: typeof import('@sf/state').getNeighborCoords
  const getRegisteredTypes: typeof import('@sf/engine').getRegisteredTypes
  const hasComponent: typeof import('@sf/state').hasComponent
  const hungerSystem: typeof import('@sf/engine').hungerSystem
  const importChunk: typeof import('@sf/engine').importChunk
  const importWorld: typeof import('@sf/engine').importWorld
  const intDiv: typeof import('@sf/state').intDiv
  const moistureSystem: typeof import('@sf/engine').moistureSystem
  const movementSystem: typeof import('@sf/engine').movementSystem
  const parseChunkKey: typeof import('@sf/state').parseChunkKey
  const posKey: typeof import('@sf/ui').posKey
  const queryEntities: typeof import('@sf/state').queryEntities
  const registerEntityType: typeof import('@sf/engine').registerEntityType
  const removeEntity: typeof import('@sf/state').removeEntity
  const removeFromSpatialIndex: typeof import('@sf/state').removeFromSpatialIndex
  const setPosition: typeof import('@sf/state').setPosition
  const simulate: typeof import('@sf/engine').simulate
  const spawnEntity: typeof import('@sf/engine').spawnEntity
  const tick: typeof import('@sf/engine').tick
  const updateSelection: typeof import('@sf/ui').updateSelection
  const updateUI: typeof import('@sf/ui').updateUI
  const zKey: typeof import('@sf/ui').zKey
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EntityId, ComponentTypes, ComponentName, Position, Health, Hunger, Speed, PlayerControlled, EntityType, Moisture, GroundCover, Name, Instance, Action, World, Face, WorldManifest, ChunkRef, ChunkData, EntitySave } from '@sf/state'
  import('@sf/state')
  // @ts-ignore
  export type { EntityTypeConstructor, System } from '@sf/engine'
  import('@sf/engine')
  // @ts-ignore
  export type { StaticSprite, AnimatedSprite, EdgeVariants, RenderContext } from '@sf/ui'
  import('@sf/ui')
}
