/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BaseEntityType: typeof import('./packages/core/src/entityTypes/BaseEntityType').BaseEntityType
  const Dirt: typeof import('./packages/core/src/entityTypes/Dirt').Dirt
  const EntityTypeTrait: typeof import('./packages/core/src/traits/EntityTypeTrait').EntityTypeTrait
  const Grass: typeof import('./packages/core/src/entityTypes/Grass').Grass
  const HealthTrait: typeof import('./packages/core/src/traits/HealthTrait').HealthTrait
  const HungerTrait: typeof import('./packages/core/src/traits/HungerTrait').HungerTrait
  const MoistureTrait: typeof import('./packages/core/src/traits/MoistureTrait').MoistureTrait
  const Player: typeof import('./packages/core/src/entityTypes/Player').Player
  const PlayerControlledTrait: typeof import('./packages/core/src/traits/PlayerControlledTrait').PlayerControlledTrait
  const PositionTrait: typeof import('./packages/core/src/traits/PositionTrait').PositionTrait
  const Sand: typeof import('./packages/core/src/entityTypes/Sand').Sand
  const SpeedTrait: typeof import('./packages/core/src/traits/SpeedTrait').SpeedTrait
  const Trait: typeof import('./packages/core/src/traits/Trait').Trait
  const Water: typeof import('./packages/core/src/entityTypes/Water').Water
  const addComponent: typeof import('./packages/core/src/ecs').addComponent
  const buildFaces2d: typeof import('./packages/core/src/faces').buildFaces2d
  const buildFaces3d: typeof import('./packages/core/src/faces').buildFaces3d
  const chunkKey: typeof import('./packages/core/src/save').chunkKey
  const createEntity: typeof import('./packages/core/src/ecs').createEntity
  const createWorld: typeof import('./packages/core/src/ecs').createWorld
  const entityTypeTickSystem: typeof import('./packages/core/src/systems/entityTypeTick').entityTypeTickSystem
  const exportChunk: typeof import('./packages/core/src/serialization').exportChunk
  const exportManifest: typeof import('./packages/core/src/serialization').exportManifest
  const getComponent: typeof import('./packages/core/src/ecs').getComponent
  const getEntitiesAt: typeof import('./packages/core/src/ecs').getEntitiesAt
  const getEntityTypeDef: typeof import('./packages/core/src/registry').getEntityTypeDef
  const getNeighborCoords: typeof import('./packages/core/src/ecs').getNeighborCoords
  const getRegisteredTypes: typeof import('./packages/core/src/registry').getRegisteredTypes
  const hasComponent: typeof import('./packages/core/src/ecs').hasComponent
  const hungerSystem: typeof import('./packages/core/src/systems/hunger').hungerSystem
  const importChunk: typeof import('./packages/core/src/serialization').importChunk
  const importWorld: typeof import('./packages/core/src/serialization').importWorld
  const moistureSystem: typeof import('./packages/core/src/systems/moisture').moistureSystem
  const movementSystem: typeof import('./packages/core/src/systems/movement').movementSystem
  const parseChunkKey: typeof import('./packages/core/src/save').parseChunkKey
  const queryEntities: typeof import('./packages/core/src/ecs').queryEntities
  const registerEntityType: typeof import('./packages/core/src/registry').registerEntityType
  const removeEntity: typeof import('./packages/core/src/ecs').removeEntity
  const simulate: typeof import('./packages/core/src/tick').simulate
  const tick: typeof import('./packages/core/src/tick').tick
}
