/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BaseEntityType: typeof import('@core/entityTypes/BaseEntityType').BaseEntityType
  const Dirt: typeof import('@core/entityTypes/Dirt').Dirt
  const EntityTypeTrait: typeof import('@core/traits/EntityTypeTrait').EntityTypeTrait
  const Grass: typeof import('@core/entityTypes/Grass').Grass
  const HealthTrait: typeof import('@core/traits/HealthTrait').HealthTrait
  const HungerTrait: typeof import('@core/traits/HungerTrait').HungerTrait
  const MoistureTrait: typeof import('@core/traits/MoistureTrait').MoistureTrait
  const Player: typeof import('@core/entityTypes/Player').Player
  const PlayerControlledTrait: typeof import('@core/traits/PlayerControlledTrait').PlayerControlledTrait
  const PositionTrait: typeof import('@core/traits/PositionTrait').PositionTrait
  const Sand: typeof import('@core/entityTypes/Sand').Sand
  const SpeedTrait: typeof import('@core/traits/SpeedTrait').SpeedTrait
  const Trait: typeof import('@core/traits/Trait').Trait
  const Water: typeof import('@core/entityTypes/Water').Water
  const addComponent: typeof import('@core/ecs').addComponent
  const buildFaces2d: typeof import('@core/faces').buildFaces2d
  const buildFaces3d: typeof import('@core/faces').buildFaces3d
  const chunkKey: typeof import('@core/save').chunkKey
  const createEntity: typeof import('@core/ecs').createEntity
  const createWorld: typeof import('@core/ecs').createWorld
  const entityTypeTickSystem: typeof import('@core/systems/entityTypeTick').entityTypeTickSystem
  const exportChunk: typeof import('@core/serialization').exportChunk
  const exportManifest: typeof import('@core/serialization').exportManifest
  const getComponent: typeof import('@core/ecs').getComponent
  const getEntitiesAt: typeof import('@core/ecs').getEntitiesAt
  const getEntityTypeConstructor: typeof import('@core/registry').getEntityTypeConstructor
  const getEntityTypeDef: typeof import('@core/registry').getEntityTypeDef
  const getNeighborCoords: typeof import('@core/ecs').getNeighborCoords
  const getRegisteredTypes: typeof import('@core/registry').getRegisteredTypes
  const hasComponent: typeof import('@core/ecs').hasComponent
  const hungerSystem: typeof import('@core/systems/hunger').hungerSystem
  const importChunk: typeof import('@core/serialization').importChunk
  const importWorld: typeof import('@core/serialization').importWorld
  const intDiv: typeof import('@core/math').intDiv
  const moistureSystem: typeof import('@core/systems/moisture').moistureSystem
  const movementSystem: typeof import('@core/systems/movement').movementSystem
  const parseChunkKey: typeof import('@core/save').parseChunkKey
  const queryEntities: typeof import('@core/ecs').queryEntities
  const registerEntityType: typeof import('@core/registry').registerEntityType
  const removeEntity: typeof import('@core/ecs').removeEntity
  const simulate: typeof import('@core/tick').simulate
  const spawnEntity: typeof import('@core/registry').spawnEntity
  const tick: typeof import('@core/tick').tick
}
