/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const addComponent: typeof import('@sf/core/ecs').addComponent
  const chunkKey: typeof import('@sf/core/save').chunkKey
  const createEntity: typeof import('@sf/core/ecs').createEntity
  const createWorld: typeof import('@sf/core/ecs').createWorld
  const exportChunk: typeof import('@sf/core/serialization').exportChunk
  const exportComponents: typeof import('@sf/core/registry').exportComponents
  const exportManifest: typeof import('@sf/core/serialization').exportManifest
  const getComponent: typeof import('@sf/core/ecs').getComponent
  const getEntitiesAt: typeof import('@sf/core/ecs').getEntitiesAt
  const getEntityTypeDef: typeof import('@sf/core/registry').getEntityTypeDef
  const getNeighborCoords: typeof import('@sf/core/ecs').getNeighborCoords
  const getRegisteredTypes: typeof import('@sf/core/registry').getRegisteredTypes
  const hasComponent: typeof import('@sf/core/ecs').hasComponent
  const hasTerrainAt: typeof import('@sf/core/ecs').hasTerrainAt
  const hungerSystem: typeof import('@sf/core/tick').hungerSystem
  const importChunk: typeof import('@sf/core/serialization').importChunk
  const importComponents: typeof import('@sf/core/registry').importComponents
  const importWorld: typeof import('@sf/core/serialization').importWorld
  const movementSystem: typeof import('@sf/core/tick').movementSystem
  const parseChunkKey: typeof import('@sf/core/save').parseChunkKey
  const queryEntities: typeof import('@sf/core/ecs').queryEntities
  const registerEntityType: typeof import('@sf/core/registry').registerEntityType
  const removeEntity: typeof import('@sf/core/ecs').removeEntity
  const simulate: typeof import('@sf/core/tick').simulate
  const tick: typeof import('@sf/core/tick').tick
}
