import fs from 'node:fs'
import path from 'node:path'

/**
 * Scan directories for exported names, distinguishing values from types.
 * Classes are emitted as both (they're usable as values and type annotations).
 */
export interface PackageExports {
  values: string[]
  types: string[]
}

function scanDir(dir: string): PackageExports {
  const valueRe = /export\s+(?:abstract\s+)?(?:async\s+)?(?:class|function|const|let|var|enum)\s+(\w+)/g
  const typeRe = /export\s+(?:interface|type)\s+(\w+)/g
  const values: string[] = []
  const types: string[] = []
  if (!fs.existsSync(dir)) return { values, types }
  for (const file of fs.readdirSync(dir)) {
    if (!file.endsWith('.ts') || file.endsWith('.d.ts')) continue
    const content = fs.readFileSync(path.join(dir, file), 'utf-8')
    for (const m of content.matchAll(valueRe)) {
      values.push(m[1])
      // Classes are usable as type annotations too.
      if (/class/.test(m[0])) types.push(m[1])
    }
    for (const m of content.matchAll(typeRe)) types.push(m[1])
  }
  return { values, types }
}

type ImportEntry = string | { name: string; type: true }
type Preset = { from: string; imports: ImportEntry[] }

interface ModuleScan {
  from: string
  exports: PackageExports
}

function makePreset(from: string, exports: PackageExports): Preset {
  return {
    from,
    imports: [
      ...exports.values,
      ...exports.types.map(t => ({ name: t, type: true as const })),
    ],
  }
}

/**
 * Scan source directories and return per-module export data.
 */
function scanModules(
  packages: Record<string, string[]>,
  aliasRoot?: string,
): ModuleScan[] {
  const modules: ModuleScan[] = []
  for (const [key, dirs] of Object.entries(packages)) {
    if (key.startsWith('~')) {
      // Per-file mapping (avoids circular imports within a package).
      const root = aliasRoot ?? ''
      for (const dir of dirs) {
        if (!fs.existsSync(dir)) continue
        for (const file of fs.readdirSync(dir)) {
          if (!file.endsWith('.ts') || file.endsWith('.d.ts')) continue
          if (file === 'index.ts') continue
          const filePath = path.join(dir, file)
          const rel = path.relative(root, filePath).replace(/\.ts$/, '')
          const from = `${key}/${rel}`
          const content = fs.readFileSync(filePath, 'utf-8')
          const exports = scanFileContent(content)
          if (exports.values.length > 0 || exports.types.length > 0) {
            modules.push({ from, exports })
          }
        }
      }
    } else {
      // Package-level mapping (cross-package).
      const merged: PackageExports = { values: [], types: [] }
      for (const dir of dirs) {
        const info = scanDir(dir)
        merged.values.push(...info.values)
        merged.types.push(...info.types)
      }
      if (merged.values.length > 0 || merged.types.length > 0) {
        modules.push({ from: key, exports: merged })
      }
    }
  }
  return modules
}

/**
 * Build an imports preset array for unplugin-auto-import.
 *
 * Keys starting with `@` are treated as **package-level** imports:
 *   all exports from all dirs are grouped under one package specifier.
 *
 * Keys starting with `~` are treated as **alias-level** imports:
 *   each file gets its own import path (`~alias/subdir/filename`),
 *   avoiding circular dependencies within a package.
 *
 * @param packages  Map of package/alias → array of source directories.
 * @param aliasRoot  For alias keys, the root dir to compute relative sub-paths.
 */
export function buildAutoImports(
  packages: Record<string, string[]>,
  aliasRoot?: string,
): Preset[] {
  return scanModules(packages, aliasRoot).map(m => makePreset(m.from, m.exports))
}

function scanFileContent(content: string): PackageExports {
  const valueRe = /export\s+(?:abstract\s+)?(?:async\s+)?(?:class|function|const|let|var|enum)\s+(\w+)/g
  const typeRe = /export\s+(?:interface|type)\s+(\w+)/g
  const values: string[] = []
  const types: string[] = []
  for (const m of content.matchAll(valueRe)) {
    values.push(m[1])
    if (/class/.test(m[0])) types.push(m[1])
  }
  for (const m of content.matchAll(typeRe)) types.push(m[1])
  return { values, types }
}

/**
 * Generate a .d.ts that declares auto-imported globals.
 *
 * Unlike unplugin-auto-import's built-in dts, this correctly handles classes:
 * they get both a `const` declaration (value position) AND a type re-export
 * (type position), so `new Foo()` and `param: Foo` both work.
 */
function generateDts(modules: ModuleScan[], typeReExports = true): string {
  const lines: string[] = [
    '/* eslint-disable */',
    '/* prettier-ignore */',
    '// @ts-nocheck',
    '// noinspection JSUnusedGlobalSymbols',
    '// Generated by auto-import scanner',
    '// biome-ignore lint: disable',
    'export {}',
  ]

  // Value declarations: const name: typeof import('...').name
  const valueDecls: string[] = []
  for (const { from, exports } of modules) {
    for (const name of exports.values) {
      valueDecls.push(`  const ${name}: typeof import('${from}').${name}`)
    }
  }
  if (valueDecls.length > 0) {
    lines.push('declare global {')
    lines.push(...valueDecls)
    lines.push('}')
  }

  // Type re-exports: classes (in both values+types) AND pure types (types only)
  // Disabled for library packages where rollupTypes needs ambient type aliases instead.
  if (typeReExports) {
    const typeModules: { from: string; types: string[] }[] = []
    for (const { from, exports } of modules) {
      if (exports.types.length > 0) {
        typeModules.push({ from, types: exports.types })
      }
    }
    if (typeModules.length > 0) {
      lines.push('// for type re-export')
      lines.push('declare global {')
      for (const { from, types } of typeModules) {
        lines.push('  // @ts-ignore')
        lines.push(`  export type { ${types.join(', ')} } from '${from}'`)
        lines.push(`  import('${from}')`)
      }
      lines.push('}')
    }
  }

  return lines.join('\n') + '\n'
}

/**
 * Vite plugin that generates a correct auto-imports.d.ts on build start.
 * Use this instead of unplugin-auto-import's `dts` option.
 *
 * @param typeReExports  Emit `export type {}` for classes so they work in type
 *   positions without `import type`. Set to `false` for library packages that
 *   use `rollupTypes` (they need ambient types.d.ts files instead).
 */
export function autoImportDtsPlugin(
  packages: Record<string, string[]>,
  aliasRoot: string,
  outPath: string,
  { typeReExports = true } = {},
) {
  return {
    name: 'auto-import-dts',
    buildStart() {
      const modules = scanModules(packages, aliasRoot)
      fs.writeFileSync(outPath, generateDts(modules, typeReExports))
    },
  }
}
