/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EntityTypeTrait: typeof import('../../core/src/traits/EntityTypeTrait').EntityTypeTrait
  const HealthTrait: typeof import('../../core/src/traits/HealthTrait').HealthTrait
  const HungerTrait: typeof import('../../core/src/traits/HungerTrait').HungerTrait
  const MoistureTrait: typeof import('../../core/src/traits/MoistureTrait').MoistureTrait
  const PlayerControlledTrait: typeof import('../../core/src/traits/PlayerControlledTrait').PlayerControlledTrait
  const PositionTrait: typeof import('../../core/src/traits/PositionTrait').PositionTrait
  const SpeedTrait: typeof import('../../core/src/traits/SpeedTrait').SpeedTrait
  const addComponent: typeof import('../../core/src/ecs').addComponent
  const buildFaces2d: typeof import('../../core/src/faces').buildFaces2d
  const buildFaces3d: typeof import('../../core/src/faces').buildFaces3d
  const chunkKey: typeof import('../../core/src/save').chunkKey
  const createEntity: typeof import('../../core/src/ecs').createEntity
  const createWorld: typeof import('../../core/src/ecs').createWorld
  const entityTypeTickSystem: typeof import('../../core/src/systems/entityTypeTick').entityTypeTickSystem
  const exportChunk: typeof import('../../core/src/serialization').exportChunk
  const exportManifest: typeof import('../../core/src/serialization').exportManifest
  const getComponent: typeof import('../../core/src/ecs').getComponent
  const getEntitiesAt: typeof import('../../core/src/ecs').getEntitiesAt
  const getEntityTypeDef: typeof import('../../core/src/registry').getEntityTypeDef
  const getNeighborCoords: typeof import('../../core/src/ecs').getNeighborCoords
  const getRegisteredTypes: typeof import('../../core/src/registry').getRegisteredTypes
  const hasComponent: typeof import('../../core/src/ecs').hasComponent
  const hungerSystem: typeof import('../../core/src/systems/hunger').hungerSystem
  const importChunk: typeof import('../../core/src/serialization').importChunk
  const importWorld: typeof import('../../core/src/serialization').importWorld
  const moistureSystem: typeof import('../../core/src/systems/moisture').moistureSystem
  const movementSystem: typeof import('../../core/src/systems/movement').movementSystem
  const parseChunkKey: typeof import('../../core/src/save').parseChunkKey
  const queryEntities: typeof import('../../core/src/ecs').queryEntities
  const registerEntityType: typeof import('../../core/src/registry').registerEntityType
  const removeEntity: typeof import('../../core/src/ecs').removeEntity
  const simulate: typeof import('../../core/src/tick').simulate
  const tick: typeof import('../../core/src/tick').tick
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EntityTypeTrait } from '../../core/src/traits/EntityTypeTrait'
  import('../../core/src/traits/EntityTypeTrait')
  // @ts-ignore
  export type { HealthTrait } from '../../core/src/traits/HealthTrait'
  import('../../core/src/traits/HealthTrait')
  // @ts-ignore
  export type { HungerTrait } from '../../core/src/traits/HungerTrait'
  import('../../core/src/traits/HungerTrait')
  // @ts-ignore
  export type { MoistureTrait } from '../../core/src/traits/MoistureTrait'
  import('../../core/src/traits/MoistureTrait')
  // @ts-ignore
  export type { PlayerControlledTrait } from '../../core/src/traits/PlayerControlledTrait'
  import('../../core/src/traits/PlayerControlledTrait')
  // @ts-ignore
  export type { PositionTrait } from '../../core/src/traits/PositionTrait'
  import('../../core/src/traits/PositionTrait')
  // @ts-ignore
  export type { SpeedTrait } from '../../core/src/traits/SpeedTrait'
  import('../../core/src/traits/SpeedTrait')
}
