/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BaseEntityType: typeof import('@sf/core/registry').BaseEntityType
  const EntityTypeTrait: typeof import('@sf/core/traits/EntityTypeTrait').EntityTypeTrait
  const HealthTrait: typeof import('@sf/core/traits/HealthTrait').HealthTrait
  const HungerTrait: typeof import('@sf/core/traits/HungerTrait').HungerTrait
  const MoistureTrait: typeof import('@sf/core/traits/MoistureTrait').MoistureTrait
  const PlayerControlledTrait: typeof import('@sf/core/traits/PlayerControlledTrait').PlayerControlledTrait
  const PositionTrait: typeof import('@sf/core/traits/PositionTrait').PositionTrait
  const SpeedTrait: typeof import('@sf/core/traits/SpeedTrait').SpeedTrait
  const Trait: typeof import('@sf/core/traits/Trait').Trait
  const addComponent: typeof import('@sf/core/ecs').addComponent
  const buildFaces2d: typeof import('@sf/core/faces').buildFaces2d
  const buildFaces3d: typeof import('@sf/core/faces').buildFaces3d
  const chunkKey: typeof import('@sf/core/save').chunkKey
  const createEntity: typeof import('@sf/core/ecs').createEntity
  const createWorld: typeof import('@sf/core/ecs').createWorld
  const entityTypeTickSystem: typeof import('@sf/core/systems/entityTypeTick').entityTypeTickSystem
  const exportChunk: typeof import('@sf/core/serialization').exportChunk
  const exportComponents: typeof import('@sf/core/registry').exportComponents
  const exportManifest: typeof import('@sf/core/serialization').exportManifest
  const getComponent: typeof import('@sf/core/ecs').getComponent
  const getEntitiesAt: typeof import('@sf/core/ecs').getEntitiesAt
  const getEntityTypeDef: typeof import('@sf/core/registry').getEntityTypeDef
  const getNeighborCoords: typeof import('@sf/core/ecs').getNeighborCoords
  const getRegisteredTypes: typeof import('@sf/core/registry').getRegisteredTypes
  const hasComponent: typeof import('@sf/core/ecs').hasComponent
  const hasTerrainAt: typeof import('@sf/core/ecs').hasTerrainAt
  const hungerSystem: typeof import('@sf/core/systems/hunger').hungerSystem
  const importChunk: typeof import('@sf/core/serialization').importChunk
  const importComponents: typeof import('@sf/core/registry').importComponents
  const importWorld: typeof import('@sf/core/serialization').importWorld
  const moistureSystem: typeof import('@sf/core/systems/moisture').moistureSystem
  const movementSystem: typeof import('@sf/core/systems/movement').movementSystem
  const parseChunkKey: typeof import('@sf/core/save').parseChunkKey
  const queryEntities: typeof import('@sf/core/ecs').queryEntities
  const registerEntityType: typeof import('@sf/core/registry').registerEntityType
  const removeEntity: typeof import('@sf/core/ecs').removeEntity
  const simulate: typeof import('@sf/core/tick').simulate
  const tick: typeof import('@sf/core/tick').tick
}
