/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by auto-import scanner
// biome-ignore lint: disable
export {}
declare global {
  const TerrainAtlas: typeof import('~rendering/TerrainAtlas').TerrainAtlas
  const WorldRenderer: typeof import('~rendering/WorldRenderer').WorldRenderer
  const Colors: typeof import('~rendering/colors').Colors
  const placeholder: typeof import('~rendering/terrainDefs').placeholder
  const CELL_W: typeof import('~rendering/types').CELL_W
  const CELL_H: typeof import('~rendering/types').CELL_H
  const TOP_H: typeof import('~rendering/types').TOP_H
  const FRONT_H: typeof import('~rendering/types').FRONT_H
  const ATLAS_ROW_H: typeof import('~rendering/types').ATLAS_ROW_H
  const TOP_VARIANT: typeof import('~rendering/types').TOP_VARIANT
  const FRONT_VARIANT: typeof import('~rendering/types').FRONT_VARIANT
  const terrainVariants: typeof import('~rendering/types').terrainVariants
  const zKey: typeof import('~rendering/types').zKey
  const posKey: typeof import('~rendering/types').posKey
  const DrawContext: typeof import('~rendering/types').DrawContext
  const DirtRenderer: typeof import('~rendering/entities/DirtRenderer').DirtRenderer
  const EntityRenderer: typeof import('~rendering/entities/EntityRenderer').EntityRenderer
  const PlayerRenderer: typeof import('~rendering/entities/PlayerRenderer').PlayerRenderer
  const SandRenderer: typeof import('~rendering/entities/SandRenderer').SandRenderer
  const StoneRenderer: typeof import('~rendering/entities/StoneRenderer').StoneRenderer
  const WaterRenderer: typeof import('~rendering/entities/WaterRenderer').WaterRenderer
}
