/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {

}
// for type re-export
declare global {
  // @ts-ignore
  export type { GameView, ViewEntity, PlayerAction, InspectResult, Game } from '~server/sdk/types'
  import('~server/sdk/types')
}
