/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by auto-import scanner
// biome-ignore lint: disable
export {}
declare global {
  const createLocalGame: typeof import('~server/sdk/localGame').createLocalGame
}
// for type re-export
declare global {
  // @ts-ignore
  export type { TraitViews, VisibleTraitName, GameView, ViewEntity, PlayerAction, InspectResult, Game } from '~server/sdk/types'
  import('~server/sdk/types')
}
