/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by auto-import scanner
// biome-ignore lint: disable
export {}
declare global {
  const bootstrap: typeof import('~engine/bootstrap').bootstrap
  const registerEntityType: typeof import('~engine/registry').registerEntityType
  const getEntityTypeConstructor: typeof import('~engine/registry').getEntityTypeConstructor
  const getRegisteredTypes: typeof import('~engine/registry').getRegisteredTypes
  const spawnEntity: typeof import('~engine/registry').spawnEntity
  const exportChunk: typeof import('~engine/serialization').exportChunk
  const exportManifest: typeof import('~engine/serialization').exportManifest
  const importChunk: typeof import('~engine/serialization').importChunk
  const importWorld: typeof import('~engine/serialization').importWorld
  const tick: typeof import('~engine/tick').tick
  const simulate: typeof import('~engine/tick').simulate
  const entityTypeTickSystem: typeof import('~engine/systems/entityTypeTick').entityTypeTickSystem
  const hungerSystem: typeof import('~engine/systems/hunger').hungerSystem
  const moistureSystem: typeof import('~engine/systems/moisture').moistureSystem
  const movementSystem: typeof import('~engine/systems/movement').movementSystem
  const EntityTypeTrait: typeof import('~engine/traits/EntityTypeTrait').EntityTypeTrait
  const GroundCoverTrait: typeof import('~engine/traits/GroundCoverTrait').GroundCoverTrait
  const HealthTrait: typeof import('~engine/traits/HealthTrait').HealthTrait
  const HungerTrait: typeof import('~engine/traits/HungerTrait').HungerTrait
  const MoistureTrait: typeof import('~engine/traits/MoistureTrait').MoistureTrait
  const MovementTrait: typeof import('~engine/traits/MovementTrait').MovementTrait
  const NameTrait: typeof import('~engine/traits/NameTrait').NameTrait
  const OccludingTrait: typeof import('~engine/traits/OccludingTrait').OccludingTrait
  const PlayerControlledTrait: typeof import('~engine/traits/PlayerControlledTrait').PlayerControlledTrait
  const PositionTrait: typeof import('~engine/traits/PositionTrait').PositionTrait
  const TickCounter: typeof import('~engine/traits/TickCounter').TickCounter
  const Trait: typeof import('~engine/traits/Trait').Trait
  const VisionTrait: typeof import('~engine/traits/VisionTrait').VisionTrait
  const BaseEntityType: typeof import('~engine/entityTypes/BaseEntityType').BaseEntityType
  const Dirt: typeof import('~engine/entityTypes/Dirt').Dirt
  const Player: typeof import('~engine/entityTypes/Player').Player
  const Sand: typeof import('~engine/entityTypes/Sand').Sand
  const Stone: typeof import('~engine/entityTypes/Stone').Stone
  const Water: typeof import('~engine/entityTypes/Water').Water
}
