/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BaseEntityType: typeof import('~engine/entityTypes/BaseEntityType').BaseEntityType
  const Dirt: typeof import('~engine/entityTypes/Dirt').Dirt
  const EntityTypeTrait: typeof import('~engine/traits/EntityTypeTrait').EntityTypeTrait
  const GroundCoverTrait: typeof import('~engine/traits/GroundCoverTrait').GroundCoverTrait
  const HealthTrait: typeof import('~engine/traits/HealthTrait').HealthTrait
  const HungerTrait: typeof import('~engine/traits/HungerTrait').HungerTrait
  const MoistureTrait: typeof import('~engine/traits/MoistureTrait').MoistureTrait
  const NameTrait: typeof import('~engine/traits/NameTrait').NameTrait
  const Player: typeof import('~engine/entityTypes/Player').Player
  const PlayerControlledTrait: typeof import('~engine/traits/PlayerControlledTrait').PlayerControlledTrait
  const PositionTrait: typeof import('~engine/traits/PositionTrait').PositionTrait
  const Sand: typeof import('~engine/entityTypes/Sand').Sand
  const SpeedTrait: typeof import('~engine/traits/SpeedTrait').SpeedTrait
  const Stone: typeof import('~engine/entityTypes/Stone').Stone
  const TICKS_PER_DAY: typeof import('@sf/state').TICKS_PER_DAY
  const Trait: typeof import('~engine/traits/Trait').Trait
  const Water: typeof import('~engine/entityTypes/Water').Water
  const addComponent: typeof import('@sf/state').addComponent
  const addToSpatialIndex: typeof import('@sf/state').addToSpatialIndex
  const bootstrap: typeof import('~engine/bootstrap').bootstrap
  const buildFaces2d: typeof import('@sf/state').buildFaces2d
  const buildFaces3d: typeof import('@sf/state').buildFaces3d
  const chunkKey: typeof import('@sf/state').chunkKey
  const createEntity: typeof import('@sf/state').createEntity
  const createWorld: typeof import('@sf/state').createWorld
  const entityTypeTickSystem: typeof import('~engine/systems/entityTypeTick').entityTypeTickSystem
  const exportChunk: typeof import('~engine/serialization').exportChunk
  const exportManifest: typeof import('~engine/serialization').exportManifest
  const getComponent: typeof import('@sf/state').getComponent
  const getEntitiesAt: typeof import('@sf/state').getEntitiesAt
  const getEntitiesInColumn: typeof import('@sf/state').getEntitiesInColumn
  const getEntityTypeConstructor: typeof import('~engine/registry').getEntityTypeConstructor
  const getNeighborCoords: typeof import('@sf/state').getNeighborCoords
  const getRegisteredTypes: typeof import('~engine/registry').getRegisteredTypes
  const hasComponent: typeof import('@sf/state').hasComponent
  const hungerSystem: typeof import('~engine/systems/hunger').hungerSystem
  const importChunk: typeof import('~engine/serialization').importChunk
  const importWorld: typeof import('~engine/serialization').importWorld
  const intDiv: typeof import('@sf/state').intDiv
  const moistureSystem: typeof import('~engine/systems/moisture').moistureSystem
  const movementSystem: typeof import('~engine/systems/movement').movementSystem
  const parseChunkKey: typeof import('@sf/state').parseChunkKey
  const queryEntities: typeof import('@sf/state').queryEntities
  const registerEntityType: typeof import('~engine/registry').registerEntityType
  const removeEntity: typeof import('@sf/state').removeEntity
  const removeFromSpatialIndex: typeof import('@sf/state').removeFromSpatialIndex
  const setPosition: typeof import('@sf/state').setPosition
  const simulate: typeof import('~engine/tick').simulate
  const spawnEntity: typeof import('~engine/registry').spawnEntity
  const tick: typeof import('~engine/tick').tick
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EntityId, ComponentTypes, ComponentName, Position, Health, Hunger, Speed, PlayerControlled, EntityType, Moisture, GroundCover, Name, Instance, Action, World, Face, WorldManifest, ChunkRef, ChunkData, EntitySave } from '@sf/state'
  import('@sf/state')
  // @ts-ignore
  export type { EntityTypeConstructor } from '~engine/registry'
  import('~engine/registry')
  // @ts-ignore
  export type { System } from '~engine/tick'
  import('~engine/tick')
}
