/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const CELL_H: typeof import('~ui/rendering/types').CELL_H
  const CELL_W: typeof import('~ui/rendering/types').CELL_W
  const DirtRenderer: typeof import('~ui/rendering/entities/DirtRenderer').DirtRenderer
  const DrawContext: typeof import('~ui/rendering/types').DrawContext
  const EntityRenderer: typeof import('~ui/rendering/entities/EntityRenderer').EntityRenderer
  const GroundCoverTraitRenderer: typeof import('~ui/rendering/traits/GroundCoverTraitRenderer').GroundCoverTraitRenderer
  const HealthTraitRenderer: typeof import('~ui/rendering/traits/HealthTraitRenderer').HealthTraitRenderer
  const HungerTraitRenderer: typeof import('~ui/rendering/traits/HungerTraitRenderer').HungerTraitRenderer
  const MoistureTraitRenderer: typeof import('~ui/rendering/traits/MoistureTraitRenderer').MoistureTraitRenderer
  const PlayerRenderer: typeof import('~ui/rendering/entities/PlayerRenderer').PlayerRenderer
  const Renderer: typeof import('~ui/renderer').Renderer
  const SandRenderer: typeof import('~ui/rendering/entities/SandRenderer').SandRenderer
  const SpeedTraitRenderer: typeof import('~ui/rendering/traits/SpeedTraitRenderer').SpeedTraitRenderer
  const StoneRenderer: typeof import('~ui/rendering/entities/StoneRenderer').StoneRenderer
  const TICKS_PER_DAY: typeof import('@sf/state').TICKS_PER_DAY
  const TraitRenderer: typeof import('~ui/rendering/traits/TraitRenderer').TraitRenderer
  const WaterRenderer: typeof import('~ui/rendering/entities/WaterRenderer').WaterRenderer
  const addComponent: typeof import('@sf/state').addComponent
  const addToSpatialIndex: typeof import('@sf/state').addToSpatialIndex
  const buildFaces2d: typeof import('@sf/state').buildFaces2d
  const buildFaces3d: typeof import('@sf/state').buildFaces3d
  const chunkKey: typeof import('@sf/state').chunkKey
  const createEntity: typeof import('@sf/state').createEntity
  const createWorld: typeof import('@sf/state').createWorld
  const getComponent: typeof import('@sf/state').getComponent
  const getEntitiesAt: typeof import('@sf/state').getEntitiesAt
  const getEntitiesInColumn: typeof import('@sf/state').getEntitiesInColumn
  const getNeighborCoords: typeof import('@sf/state').getNeighborCoords
  const hasComponent: typeof import('@sf/state').hasComponent
  const intDiv: typeof import('@sf/state').intDiv
  const parseChunkKey: typeof import('@sf/state').parseChunkKey
  const posKey: typeof import('~ui/rendering/types').posKey
  const queryEntities: typeof import('@sf/state').queryEntities
  const removeEntity: typeof import('@sf/state').removeEntity
  const removeFromSpatialIndex: typeof import('@sf/state').removeFromSpatialIndex
  const setPosition: typeof import('@sf/state').setPosition
  const updateSelection: typeof import('~ui/sidebar').updateSelection
  const updateUI: typeof import('~ui/sidebar').updateUI
  const zKey: typeof import('~ui/rendering/types').zKey
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EntityId, ComponentTypes, ComponentName, Position, Health, Hunger, Speed, PlayerControlled, EntityType, Moisture, GroundCover, Name, Instance, Action, World, Face, WorldManifest, ChunkRef, ChunkData, EntitySave } from '@sf/state'
  import('@sf/state')
  // @ts-ignore
  export type { StaticSprite, AnimatedSprite, EdgeVariants, RenderContext } from '~ui/rendering/types'
  import('~ui/rendering/types')
}
