/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by auto-import scanner
// biome-ignore lint: disable
export {}
declare global {
  const listSaves: typeof import('~editor/connection').listSaves
  const loadWorld: typeof import('~editor/connection').loadWorld
  const saveWorld: typeof import('~editor/connection').saveWorld
  const createWorld: typeof import('~editor/connection').createWorld
  const EditorRenderer: typeof import('~editor/renderer').EditorRenderer
  const world: typeof import('~editor/world').world
  const currentSaveName: typeof import('~editor/world').currentSaveName
  const editorLoadWorld: typeof import('~editor/world').editorLoadWorld
  const editorSaveWorld: typeof import('~editor/world').editorSaveWorld
  const placeEntity: typeof import('~editor/world').placeEntity
  const deleteEntities: typeof import('~editor/world').deleteEntities
  const getEntities: typeof import('~editor/world').getEntities
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EditorRenderer } from '~editor/renderer'
  import('~editor/renderer')
}
