/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by auto-import scanner
// biome-ignore lint: disable
export {}
declare global {
  const TICKS_PER_DAY: typeof import('~state/ecs').TICKS_PER_DAY
  const createWorld: typeof import('~state/ecs').createWorld
  const createEntity: typeof import('~state/ecs').createEntity
  const addComponent: typeof import('~state/ecs').addComponent
  const getComponent: typeof import('~state/ecs').getComponent
  const hasComponent: typeof import('~state/ecs').hasComponent
  const removeEntity: typeof import('~state/ecs').removeEntity
  const queryEntities: typeof import('~state/ecs').queryEntities
  const getEntitiesAt: typeof import('~state/ecs').getEntitiesAt
  const getEntitiesInColumn: typeof import('~state/ecs').getEntitiesInColumn
  const addToSpatialIndex: typeof import('~state/ecs').addToSpatialIndex
  const removeFromSpatialIndex: typeof import('~state/ecs').removeFromSpatialIndex
  const setPosition: typeof import('~state/ecs').setPosition
  const getNeighborCoords: typeof import('~state/ecs').getNeighborCoords
  const buildFaces2d: typeof import('~state/faces').buildFaces2d
  const buildFaces3d: typeof import('~state/faces').buildFaces3d
  const intDiv: typeof import('~state/math').intDiv
  const chunkKey: typeof import('~state/save').chunkKey
  const parseChunkKey: typeof import('~state/save').parseChunkKey
}
