/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const TICKS_PER_DAY: typeof import('~state/ecs').TICKS_PER_DAY
  const addComponent: typeof import('~state/ecs').addComponent
  const addToSpatialIndex: typeof import('~state/ecs').addToSpatialIndex
  const buildFaces2d: typeof import('~state/faces').buildFaces2d
  const buildFaces3d: typeof import('~state/faces').buildFaces3d
  const chunkKey: typeof import('~state/save').chunkKey
  const createEntity: typeof import('~state/ecs').createEntity
  const createWorld: typeof import('~state/ecs').createWorld
  const getComponent: typeof import('~state/ecs').getComponent
  const getEntitiesAt: typeof import('~state/ecs').getEntitiesAt
  const getEntitiesInColumn: typeof import('~state/ecs').getEntitiesInColumn
  const getNeighborCoords: typeof import('~state/ecs').getNeighborCoords
  const hasComponent: typeof import('~state/ecs').hasComponent
  const intDiv: typeof import('~state/math').intDiv
  const parseChunkKey: typeof import('~state/save').parseChunkKey
  const queryEntities: typeof import('~state/ecs').queryEntities
  const removeEntity: typeof import('~state/ecs').removeEntity
  const removeFromSpatialIndex: typeof import('~state/ecs').removeFromSpatialIndex
  const setPosition: typeof import('~state/ecs').setPosition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EntityId, ComponentTypes, ComponentName, Position, Health, Hunger, Speed, PlayerControlled, EntityType, Moisture, GroundCover, Name, Instance, Action, World } from '~state/ecs'
  import('~state/ecs')
  // @ts-ignore
  export type { Face } from '~state/faces'
  import('~state/faces')
  // @ts-ignore
  export type { WorldManifest, ChunkRef, ChunkData, EntitySave } from '~state/save'
  import('~state/save')
}
